### PR TITLE
Fix fingerprint and lock icon on build kept forever

### PR DESCRIPTION
**Pull request by nfalco79**
Fix fingerprint color from black to grey and fix the lock icon on build kept forever that was missing.

### CODE REVIEW

**Comment by afonsof** [comment]
Ho @nfalco79, Don't you prefer to use this Material Design icon:
image https://design.google.com/icons/#ic_build

**Comment by nfalco79** [comment]
It was my first choice but I had use that one in PR because is more similar to the original.
As you prefer I will change it.
The build icon could be used for missing Parameters/Enviroment Variables that have a build icon on paper.

**Comment by nfalco79** [comment]
Update commit with the icon you propose.

PS: it's not clear how to build you theme since you split project.

**Comment by afonsof** [comment]
I'm sorry for taking too much time to reply you. This week was busy. Now the core is a npm module. So after modified it must be updated in npm and in the theme module. It became a little bit complex so I'll update the Readme file to help people how to handle this.

**Comment by nfalco79** [comment]
what about the icon?

**Pull request merged**
